name: Lisa Nathan Photography
favicon: null
layout_spectrum: 0.8751
typography_spectrum: 0.17954
title: Lisa Nathan Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23559c'
    - '#4680c0'
    - '#abb1d1'
    - '#403636'
    - '#0a0c00'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
