name: Lisa Nathan Photography
favicon: null
layout_spectrum: 0.49479397502727807
typography_spectrum: 0.2824521728325635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.16746920417062938
  lightness: 0.17054162500426173
  saturation: 0.1820784907322377
  rhythmicContrast: 0.9737642158288509
purpose: []
