name: Lisa Nathan Photography
favicon: null
layout_spectrum: 0.49479397502727807
typography_spectrum: 0.2824521728325635
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8ebfe0'
    - '#0c0c0a'
    - '#f1eff0'
    - '#5c5426'
    - '#a7ae3e'
  brandStrength: 0.4375
  lightness: 0.5625
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
